# Qasim Shafiq
# 20i1783

### References
https://scikit-learn.org/
https://stackabuse.com/

In [129]:
!pip install opencv-python

In [39]:
import pandas as pd
import keras
from zipfile import ZipFile
from pyunpack import Archive
from pydub import AudioSegment
import os, zipfile
import pandas as pd
import numpy as np
import librosa
import path
from pathlib import Path
from sklearn.model_selection import train_test_split
from tqdm import tqdm
import keras.utils as image
# and use 
# image.ImageDataGenerator()
# image.load_img()
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras.utils import to_categorical
import matplotlib.pyplot as plt


# Creating two data frames

In [87]:
df_1 = pd.read_csv('labels.csv')
df_1.drop('text_ocr', inplace = True, axis =1)
df_1.drop('text_corrected', inplace = True, axis =1)
df_2 = pd.read_csv('labels.csv')

In [92]:
df_1.head()

Unnamed: 0    image_name overall_sentiment
0           0   image_1.jpg     very_positive
1           1  image_2.jpeg     very_positive
2           2   image_3.JPG          positive
3           3   image_4.png          positive
4           4   image_5.png           neutral

In [91]:
df_2.drop('text_ocr', inplace = True, axis =1)
df_2.drop('image_name', inplace = True, axis =1)
df_2.head()

Unnamed: 0                                     text_corrected  \
0           0  LOOK THERE MY FRIEND LIGHTYEAR NOW ALL SOHALIK...   
1           1  The best of #10 YearChallenge! Completed in le...   
2           2  Sam Thorne @Strippin ( Follow Follow Saw every...   
3           3              10 Year Challenge - Sweet Dee Edition   
4           4  10 YEAR CHALLENGE WITH NO FILTER 47 Hilarious ...   

  overall_sentiment  
0     very_positive  
1     very_positive  
2          positive  
3          positive  
4           neutral

In [34]:
df_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6992 entries, 0 to 6991
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   Unnamed: 0         6992 non-null   int64 
 1   image_name         6992 non-null   object
 2   text_ocr           6831 non-null   object
 3   text_corrected     6987 non-null   object
 4   overall_sentiment  6992 non-null   object
dtypes: int64(1), object(4)
memory usage: 273.2+ KB


In [134]:
import cv2
os.chdir(r"C:\Users\hp\Desktop\Uni\IDS\ ")
os.listdir()
img=df_1['image_name']

# Image Processing

## Selecting Independent and Dependent Variables

In [141]:
from skimage.transform import resize
from skimage import filters
from PIL import Image,ImageOps,ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True
images = []

for i in img:
    print(i)
    image = Image.open('C:\\Users\\hp\\Desktop\\Uni\\IDS\\images'+'\\'+i)
    image = image.resize((200,200))
    gray_image = ImageOps.grayscale(image)
    expanded_image_grayscale = np.expand_dims(gray_image, axis=2)
    image_flat = np.array(expanded_image_grayscale).flatten()
    images.append(image_flat)
  

image_1.jpg
image_2.jpeg
image_3.JPG
image_4.png
image_5.png
image_6.jpg
image_7.png
image_8.jpg
image_9.jpg
image_10.png
image_11.jpg
image_12.jpg
image_13.png
image_14.png
image_15.jpg
image_16.png
image_17.jpg
image_18.jpg
image_19.png
image_20.png
image_21.jpg
image_22.jpg
image_23.jpeg
image_24.jpg
image_25.jpg
image_26.jpeg
image_27.jpeg
image_28.jpg
image_29.jpg
image_30.jpg
image_31.jpg
image_32.jpg
image_33.jpg
image_34.jpg
image_35.png
image_36.jpg
image_37.png
image_38.jpg
image_39.png
image_40.jpg
image_41.PNG
image_42.jpg
image_43.jpeg
image_44.jpg
image_45.jpeg
image_46.jpg
image_47.jpg
image_48.jpg
image_49.png
image_50.jpg
image_51.jpg
image_52.jpg
image_53.jpg
image_54.jpg
image_55.jpg
image_56.jpg
image_57.jpg
image_58.jpg
image_59.jpg
image_60.jpg
image_61.jpg
image_62.jpg
image_63.png
image_64.jpg
image_65.jpg
image_66.jpg
image_67.jpg
image_68.jpg
image_69.jpeg
image_70.jpg
image_71.jpg
image_72.jpg
image_73.png
image_74.jpg
image_75.jpg
image_76.png
image_77.jpeg


C:\Users\hp\anaconda3\lib\site-packages\PIL\Image.py:945: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(


image_6683.jpg
image_6684.jpg
image_6685.jpg
image_6686.jpg
image_6687.png
image_6688.jpg
image_6689.jpg
image_6690.png
image_6691.png
image_6692.jpg
image_6693.jpg
image_6694.jpg
image_6695.jpg
image_6696.jpg
image_6697.jpg
image_6698.png
image_6699.jpg
image_6700.png
image_6701.jpg
image_6702.jpg
image_6703.png
image_6704.png
image_6705.png
image_6706.jpg
image_6707.jpg
image_6708.png
image_6709.png
image_6710.jpeg
image_6711.jpeg
image_6712.jpg
image_6713.jpg
image_6714.png
image_6715.png
image_6716.png
image_6717.jpg
image_6718.png
image_6719.png
image_6720.png
image_6721.jpg
image_6722.jpg
image_6723.jpg
image_6724.jpg
image_6725.jpg
image_6726.jpg
image_6727.jpg
image_6728.jpg
image_6729.png
image_6730.jpg
image_6731.jpg
image_6732.jpg
image_6733.jpg
image_6734.jpg
image_6735.png
image_6736.jpg
image_6737.jpeg
image_6738.jpg
image_6739.jpeg
image_6740.jpg
image_6741.jpg
image_6742.jpg
image_6743.png
image_6744.png
image_6745.jpg
image_6746.jpg
image_6747.png
image_6748.png
image_

# Image Preprocessing

## Normalization

In [159]:
data=[]
data=images
y = (data-np.min(data))/(np.max(data)-np.min(data))

In [157]:
y

[array([108, 108, 108, ...,  92,  91,  91], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([ 45,  40,  31, ..., 127, 127, 127], dtype=uint8),
 array([108, 111, 105, ..., 255, 255, 255], dtype=uint8),
 array([252, 252, 252, ..., 255, 255, 255], dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 array([249, 249, 249, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 146,  98,  74], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 244, 243, 240], dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 array([255, 255, 255, ...,  40,  57,  80], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 135, 137, 174], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([ 59,  95,  84, ..., 152, 157,  93], dtype=uint8),
 array([246, 251, 247, ...,  43,  48,  58], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 

In [137]:
labels = df_1['overall_sentiment'] 
x=[]
for i in labels:
    if(i == 'very_positive'):
        x.append(0)
    if(i == 'positive'):
        x.append(0)
    if(i == 'negative'):
        x.append(2)
    if(i == 'very_negative'):
        x.append(2)
    if(i == 'neutral'):    
        x.append(1)

In [138]:
x

[0,
 0,
 0,
 0,
 1,
 2,
 2,
 1,
 0,
 0,
 2,
 0,
 0,
 0,
 2,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 2,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 2,
 0,
 0,
 0,
 2,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 2,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 2,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 2,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 2,
 0,
 0,
 0,
 0,
 1,
 2,
 0,
 0,
 0,
 2,
 0,
 0,
 2,
 0,
 1,
 0,
 0,
 0,
 0,
 2,
 1,
 0,
 0,
 1,
 0,
 2,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 2,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 2,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,


# Machine Learning Models

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(y[:1500],x[:1500],test_size=0.2,random_state=42)

## Random Forrest Classifier

In [173]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
clf = RandomForestClassifier()
clf = clf.fit(x_train[:1500], y_train[:1500])
pred=clf.predict(x_test[:1500])
print (pred)
clf.score(x_test,y_test)

[1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 1 0]


0.6133333333333333

In [174]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import classification_report 
print ("Accuracy : " , accuracy_score(y_test[:1500],pred)*100)  
print("Report : \n", classification_report(y_test[:1500], pred))
print("F1 Score : ",f1_score(y_test[:1500], pred, average='weighted')*100)
print("Confusion Matrix\n: ",confusion_matrix(y_test[:1500],pred))

Accuracy :  61.33333333333333
Report : 
               precision    recall  f1-score   support

           0       0.62      0.96      0.75       186
           1       0.43      0.06      0.11        97
           2       0.00      0.00      0.00        17

    accuracy                           0.61       300
   macro avg       0.35      0.34      0.29       300
weighted avg       0.52      0.61      0.50       300

F1 Score :  50.258207359902265
Confusion Matrix
:  [[178   8   0]
 [ 91   6   0]
 [ 17   0   0]]


C:\Users\hp\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\hp\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\hp\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## Decision Tree Classifier

In [194]:
from sklearn.tree import DecisionTreeClassifier
clf2 = DecisionTreeClassifier()
clf2 = clf2.fit(x_train[:1500],y_train[:1500])
pred2=clf2.predict(x_test[:1500])
clf2.score(x_test,y_test)

0.4766666666666667

In [195]:
print ("Accuracy : " , accuracy_score(y_test[:1500],pred2)*100)  
print("Report : \n", classification_report(y_test[:1500], pred2))
print("F1 Score : ",f1_score(y_test[:1500], pred2, average='weighted')*100)
print("Confusion Matrix\n: ",confusion_matrix(y_test[:1500],pred2))

Accuracy :  47.66666666666667
Report : 
               precision    recall  f1-score   support

           0       0.63      0.58      0.60       186
           1       0.32      0.34      0.33        97
           2       0.10      0.18      0.13        17

    accuracy                           0.48       300
   macro avg       0.35      0.36      0.35       300
weighted avg       0.50      0.48      0.49       300

F1 Score :  48.8373964125588
Confusion Matrix
:  [[107  62  17]
 [ 55  33   9]
 [  7   7   3]]


## Support Vector Classifier

In [279]:
from sklearn.ensemble import BaggingClassifier
clf3 = BaggingClassifier()
clf3 = clf3.fit(x_train[:1500],y_train[:1500])
pred3=clf3.predict(x_test[:1500])
print (pred3)
clf3.score(x_test,y_test)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 1 1 1 0 0 0 0 1 2 0 0 0 1 0 0 0 0
 0 1 0 2 0 1 0 0 0 1 1 0 2 0 0 1 0 0 0 1 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0
 0 0 1 1 0 0 0 0 0 0 0 0 1 0 1 0 0 1 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0
 0 0 0 1 0 0 1 1 0 0 0 1 1 1 1 1 1 0 0 0 1 0 0 0 1 0 1 0 0 0 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 0 0 0 0 0 1 0 1 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0
 2 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0]


0.5533333333333333

In [280]:
print ("Accuracy : " , accuracy_score(y_test[:1500],pred3)*100)  
print("Report : \n", classification_report(y_test[:1500], pred3))
print("F1 Score : ",f1_score(y_test[:1500], pred3, average='weighted')*100)
print("Confusion Matrix\n: ",confusion_matrix(y_test[:1500],pred3))

Accuracy :  55.333333333333336
Report : 
               precision    recall  f1-score   support

           0       0.62      0.80      0.70       186
           1       0.31      0.18      0.23        97
           2       0.00      0.00      0.00        17

    accuracy                           0.55       300
   macro avg       0.31      0.33      0.31       300
weighted avg       0.49      0.55      0.51       300

F1 Score :  50.65124521966234
Confusion Matrix
:  [[149  34   3]
 [ 77  17   3]
 [ 14   3   0]]


In [202]:
from sklearn.feature_extraction.text import CountVectorizer
import nltk
from nltk import WordNetLemmatizer
from nltk.stem import PorterStemmer
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import HashingVectorizer
import string

# Text Processing

## Selecting Independent and Dependent Variables

In [203]:
df_2.isna()
df_2

Unnamed: 0                                     text_corrected  \
0              0  LOOK THERE MY FRIEND LIGHTYEAR NOW ALL SOHALIK...   
1              1  The best of #10 YearChallenge! Completed in le...   
2              2  Sam Thorne @Strippin ( Follow Follow Saw every...   
3              3              10 Year Challenge - Sweet Dee Edition   
4              4  10 YEAR CHALLENGE WITH NO FILTER 47 Hilarious ...   
...          ...                                                ...   
6987        6987  Tuesday is Mardi Gras Wednesday is Valentine's...   
6988        6988  MUST WATCH MOVIES OF 2017 ITI Chennai memes MA...   
6989        6989  LESS MORE TALKING PLANNING SODA JUNK FOOD COMP...   
6990        6990  When I have time is a fantasy. no one has time...   
6991        6991  The starting point for every good idea is "Wha...   

     overall_sentiment  
0        very_positive  
1        very_positive  
2             positive  
3             positive  
4              neutral  
...                ...  
6987           neutral  
6988           neutral  
6989          positive  
6990     very_positive  
6991          positive  

[6992 rows x 3 columns]

In [201]:
df_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6992 entries, 0 to 6991
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   Unnamed: 0         6992 non-null   int64 
 1   text_corrected     6987 non-null   object
 2   overall_sentiment  6992 non-null   object
dtypes: int64(1), object(2)
memory usage: 164.0+ KB


In [222]:
Y=[]
for i in labels:
    if(i == 'very_positive'):
        Y.append(0)
    if(i == 'positive'):
        Y.append(0)
    if(i == 'negative'):
        Y.append(2)
    if(i == 'very_negative'):
        Y.append(2)
    if(i == 'neutral'):    
        Y.append(1)

In [223]:
Text=df_2.text_corrected

In [224]:
DOC=[]

# Text Preprocessing

In [225]:
import re
from nltk.stem import WordNetLemmatizer
stemmer = WordNetLemmatizer()

for sen in range(0, len(Text)):
    # Remove all the special characters
    document = re.sub(r'\W', ' ', str(Text[sen]))
    
    # remove all single characters
    document = re.sub(r'\s+[a-zA-Z]\s+', ' ', document)
    
    # Remove single characters from the start
    document = re.sub(r'\^[a-zA-Z]\s+', ' ', document) 
    
    # Substituting multiple spaces with single space
    document = re.sub(r'\s+', ' ', document, flags=re.I)
    
    # Removing prefixed 'b'
    document = re.sub(r'^b\s+', '', document)
    
    # Converting to Lowercase
    document = document.lower()
    
    # Lemmatization
    document = document.split()

    document = [stemmer.lemmatize(word) for word in document]
    document = ' '.join(document)
    
    DOC.append(document)

In [226]:
DOC

['look there my friend lightyear now all sohalikut trend play the 10 year challenge at facebook imgflip com',
 'the best of 10 yearchallenge completed in le the 4 year kudu to narendramodi ji 8 05 pm 16 jan 2019 from mumbai india',
 'sam thorne strippin follow follow saw everyone posting these 2009 v 2019 pic so here mine 6 23 pm 12 jan 2019 636 retweets 3 224 like 65 636 3 2k',
 '10 year challenge sweet dee edition',
 '10 year challenge with no filter 47 hilarious 10 year challenge meme what is 10 year challenge',
 '1998 don get in car with stranger 2008 don meet people from the internet alone memecenter com 2019 uber order yourself stranger from the internet to get into car with alone',
 '10 year challenge is lit af üs erg 1945 1955 wow such transformation',
 '10 year challenge emotional edition boredpanda com',
 'fornite died in 10 month but minecraft never died in 10 year am so proud of this community',
 'facebook 10 year challenge ploy or simple meme mo by exo hạ minh le 18 jan 20

## Bag of Words

In [220]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(max_features=1500, min_df=5, max_df=0.7, stop_words=stopwords.words('english'))
X = vectorizer.fit_transform(DOC).toarray()

## TfidTransformer

In [227]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidf = TfidfTransformer()
X = tfidf.fit_transform(X).toarray()

In [235]:
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

# Machine Learning Models

In [238]:
x_train2,x_test2,y_train2,y_test2 = train_test_split(X[:1500],Y[:1500],test_size=0.2,random_state=42)

## KNN Classifier

In [263]:
from sklearn.neighbors import KNeighborsClassifier
clf4 = KNeighborsClassifier()
clf4 = clf4.fit(x_train2[:1500], y_train2[:1500])
pred4=clf4.predict(x_test2[:1500])
print (pred4)
clf4.score(x_test2,y_test2)

[1 1 0 0 0 0 1 0 0 1 0 1 1 0 1 0 0 0 0 0 0 1 0 1 1 0 0 1 1 1 1 0 1 1 0 1 0
 0 1 1 0 0 1 1 1 1 0 0 0 1 0 1 1 0 1 1 0 1 0 2 1 1 0 1 0 1 1 1 0 0 1 1 1 1
 1 1 0 1 0 0 0 1 0 1 1 0 1 0 1 1 0 1 1 1 0 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 1 1 0 0 0 0 0 0 0 0 1 1 1 0 1 1 0 1 1 0 0 0 0 0 0 0 1 1 1 1 0 0 1 0 1 0
 1 1 0 0 1 1 0 0 1 1 0 0 1 0 1 0 1 1 0 0 1 0 1 1 1 0 0 0 1 0 1 1 0 0 0 1 0
 1 0 0 1 0 0 0 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 1 0 1 1 0 1 0 0 0 1 0 0 0 0 0
 0 0 1 0 1 0 1 0 0 0 0 1 1 1 1 0 1 1 1 0 1 1 0 1 0 1 1 0 0 0 0 0 0 1 0 0 1
 1 0 1 0 1 1 0 0 0 0 1 1 1 1 0 0 0 1 0 0 1 0 1 0 0 1 0 0 0 1 0 0 0 1 0 0 1
 0 0 1 1]


0.5166666666666667

In [264]:
print ("Accuracy : " , accuracy_score(y_test2[:1500],pred4)*100)  
print("Report : \n", classification_report(y_test2[:1500], pred4))
print("F1 Score : ",f1_score(y_test2[:1500], pred4, average='weighted')*100)
print("Confusion Matrix\n: ",confusion_matrix(y_test2[:1500],pred4))

Accuracy :  51.66666666666667
Report : 
               precision    recall  f1-score   support

           0       0.64      0.56      0.60       186
           1       0.37      0.53      0.44        97
           2       0.00      0.00      0.00        17

    accuracy                           0.52       300
   macro avg       0.34      0.36      0.34       300
weighted avg       0.52      0.52      0.51       300

F1 Score :  51.1514883583849
Confusion Matrix
:  [[104  81   1]
 [ 46  51   0]
 [ 12   5   0]]


## MultinomialNB

In [248]:
from sklearn.naive_bayes import MultinomialNB
clf5 = MultinomialNB()
clf5 = clf5.fit(x_train2[:1500], y_train2[:1500])
pred5=clf5.predict(x_test2[:1500])
print (pred5)
clf5.score(x_test2,y_test2)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0
 0 0 0 0]


0.6066666666666667

In [249]:
print ("Accuracy : " , accuracy_score(y_test2[:1500],pred5)*100)  
print("Report : \n", classification_report(y_test2[:1500], pred5))
print("F1 Score : ",f1_score(y_test2[:1500], pred5, average='weighted')*100)
print("Confusion Matrix\n: ",confusion_matrix(y_test2[:1500],pred5))

Accuracy :  60.66666666666667
Report : 
               precision    recall  f1-score   support

           0       0.62      0.96      0.76       186
           1       0.25      0.03      0.06        97
           2       0.00      0.00      0.00        17

    accuracy                           0.61       300
   macro avg       0.29      0.33      0.27       300
weighted avg       0.47      0.61      0.49       300

F1 Score :  48.60682073317075
Confusion Matrix
:  [[179   7   0]
 [ 94   3   0]
 [ 15   2   0]]


C:\Users\hp\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\hp\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\hp\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## SGD Classifier

In [246]:
from sklearn.linear_model import SGDClassifier
clf6 = SGDClassifier()
clf6 = clf6.fit(x_train2[:1500], y_train2[:1500])
pred6=clf6.predict(x_test2[:1500])
print (pred6)
clf6.score(x_test2,y_test2)

[0 0 0 1 0 0 0 0 0 0 1 2 0 0 0 0 1 0 0 0 0 1 2 1 0 0 0 0 0 0 1 1 1 1 0 0 1
 0 1 0 0 0 1 0 0 1 0 1 1 0 0 0 1 0 1 0 0 2 1 0 0 0 0 0 1 0 0 1 0 0 1 0 0 0
 1 1 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0 2 1 0 0 0 0 1 0 0 0 0 0 0
 0 1 0 1 0 0 0 0 0 1 0 0 0 1 1 0 1 0 0 1 0 0 1 1 0 0 0 0 0 1 0 0 0 0 1 0 0
 0 1 0 0 1 0 0 1 0 0 1 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 0 1 0 1 0 0 0 0 0 0 1
 0 0 0 0 1 0 1 1 0 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 1 1 0 2 0 0 2 0
 0 1 0 0 0 0 0 1 1 0 1 0 0 1 1 0 0 1 1 0 1 2 0 1 1 0 0 0 0 0 1 0 2 0 0 0 0
 0 0 0 1 0 1 1 1 0 1 0 0 1 1 0 1 1 0 0 1 0 0 0 0 0 0 0 0 1 0 1 1 0 1 0 0 1
 0 0 1 2]


0.5266666666666666

In [247]:
print ("Accuracy : " , accuracy_score(y_test2[:1500],pred6)*100)  
print("Report : \n", classification_report(y_test2[:1500], pred6))
print("F1 Score : ",f1_score(y_test2[:1500], pred6, average='weighted')*100)
print("Confusion Matrix\n: ",confusion_matrix(y_test2[:1500],pred6))

Accuracy :  52.666666666666664
Report : 
               precision    recall  f1-score   support

           0       0.63      0.69      0.66       186
           1       0.34      0.31      0.32        97
           2       0.00      0.00      0.00        17

    accuracy                           0.53       300
   macro avg       0.32      0.33      0.33       300
weighted avg       0.50      0.53      0.51       300

F1 Score :  51.28854304175642
Confusion Matrix
:  [[128  52   6]
 [ 64  30   3]
 [ 11   6   0]]


# Calculating Overall F1 Score

In [281]:
Total_Score = f1_score(y_test2[:1500], pred6, average='weighted')*100
Total_Score += f1_score(y_test2[:1500], pred5, average='weighted')*100
Total_Score += f1_score(y_test2[:1500], pred4, average='weighted')*100
Total_Score += f1_score(y_test[:1500], pred3, average='weighted')*100
Total_Score += f1_score(y_test[:1500], pred2, average='weighted')*100
Total_Score += f1_score(y_test[:1500], pred, average='weighted')*100

In [282]:
Overall_F1_score=Total_Score/6

In [283]:
print("Overall F1 Score : ", Overall_F1_score)

Overall F1 Score :  50.13228352090592


# Saving Model For Flask

In [288]:
import pickle
pickle.dump(pred, open("model.pkl", "wb"))